[tool.poetry]
name = "talki"
version = "0.1.0"
description = ""
authors = ["chun1 <arthur@chunai.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
